import numpy as np
a=np.array([1,2,3,4,5])
print("数组本身",a)
print("类型",type(a))
print("形状 shape:",a.shape)
print("维度 ndim:",a.ndim)
print("元素个数 size:",a.size)
b=np.array([[1,2,3],[4,5,6]])
print("二维数组: \n",b)
print("二维形状：",b.shape)
c=np.zeros((3,4))
print("全0数组:\n",c)
d=np.ones((2,3))
print("全1数组:\n",d)
e=np.arange(10)
print("随机数组：\n",e)
a=np.array([1,2,3,4])
b=np.array([10,20,30,40])
print("加法a+b:",a+b)
print("减法a-b:",a-b)
print("乘法a*b:",a*b)
print("除法a/b:",a/b)
print("平方:",a**b)
print("大于2的判断:",a>2)
print("求和:",a.sum())
print("最大值:",a.max())
print("最小值:",a.min())