import numpy as np
a=np.arange(2,14).reshape(3,4)
print(a)
print("最小值:",np.argmin(a))
print("最大值:",np.argmax(a))
print("平均值:",np.average(a))
print("中位数:",np.median(a))
print("累加:",np.cumsum(a))
print("累差:",np.diff(a))
print("非零数:",np.nonzero(a))
b=np.arange(14,2,-1).reshape(3,4)
print("排序:",np.sort(b))
print("列计算:",np.mean(b,axis=0))
print("行计算:",np.mean(b,axis=1))
print(np.clip(b,6,10))
print("翻转:",b.T)
c=np.arange(1,13)
print(c[4])
d=np.arange(1,13).reshape(3,4)
print(d)
print(d[1,1])
print(d[1,:])
print(d[:,1])
for row in d:
    print(row)
for column in d.T:
    print(column)
for item in d.flat:
    print(item)