import pandas as pd 
df=pd.read_csv("data/wugongshan_weather.csv")
print("前5行:",df.head())
print("\n一共多少行多少列:",df.shape)
print("\n每列的数据类型:",df.dtypes)
print("\n每列有多少个空值：")
print(df.isna().sum())
df["降水量"]=df["降水量"].fillna(0)
df["最低气温"] = df["最低气温"].fillna(df["最低气温"].mean())
print("\n清洗之后还有空值吗：",df.isna().sum())
print("\n===== describe =====")
print(df.describe)
i=df["最高气温"].idxmax()
print("最热的一天:",df.loc[i,"日期"],df.loc[i,"最高气温"])
rain_days=(df["降水量"]>0).sum()
print("降水量大于0的天数:",rain_days,",占",round(rain_days/len(df)*100,1),"%")
rain_days2 = (df["降水量"] > 1).sum()
print("降水量>1mm 的天数：", rain_days2, "，占", round(rain_days2 / len(df) * 100, 1), "%")
df["月份"]=df["日期"].str[5:7]
print("\n每月降水量合计：")
print(df.groupby("月份")["降水量"].sum())
print("\n每月平均最高气温：")
print(df.groupby("月份")["最高气温"].mean())
print("\n每个月各有几天数据：")
print(df.groupby("月份")["日期"].count())